Remove `small` feature
hashintel/hash pull request #1054
Opened 2022-09-11 10:39 UTC by TimDiekmann

## 🌟 What is the purpose of this PR?

`SmallVec` stores elements inline if only the specified amount of items are stored at most. This is an optimization, which only applies in the unhappy path. In particular, with #1053, this is not an optimization anymore as `Frame` is now bigger than 16 bytes in size (on architectures with 64 bit pointer width).

2022-09-11 10:40 UTC, indietyp requested changes
This is still missing the removal of the `small` feature in the `lib.rs` table, I believe.

2022-09-11 10:42 UTC, TimDiekmann commented
Good point thanks 🙂 
Removed that row in 428e62426a000af9f7b1f1a8afe9478762e385d6

2022-09-11 10:44 UTC, indietyp approved these changes

2022-09-13 13:56 UTC, Alfred-Mountfield approved these changes
On the whole this seems the right way to go. Shame though

2022-09-13 15:05 UTC, merged