Fix messages package Python component init
hashintel/hash pull request #116
Opened 2021-12-20 10:56 UTC by litvand

## 🌟 What is the purpose of this PR?

Python init PR #5

## 🔗 Related links

- [Asana task description](https://app.asana.com/0/0/1201539039235286/f)

## 🔍 What does this change?

* Fixes syntax

## 🛡 Tests

- ✅ Manual Tests

## ❓ How to test this?

1. Run any experiment.
2. Python should get through messages package init and reach NewSimulationRun message handling

2021-12-20 11:32 UTC, Alfred-Mountfield requested changes
Blocking until https://github.com/hashintel/hash/pull/115 is merged and this branch is rebased for easier review

2022-01-06 15:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hashintel/hash?pullRequest=116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hashintel/hash?pullRequest=116) before we can accept your contribution.<br/><hr/>**litvand** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hashintel/hash?pullRequest=116) it.</sub>

2022-01-07 13:41 UTC, Alfred-Mountfield approved these changes

2022-01-07 13:46 UTC, TimDiekmann approved these changes

2022-01-07 13:46 UTC, merged