Implement creating entity type functionality
hashintel/hash pull request #1169
Opened 2022-10-05 16:47 UTC by nathggns

## 🌟 What is the purpose of this PR?

Add ability to create an entity type to the entity type editor

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1202953520344821/1203109490608734/f) _(internal)_

## 🚫 Blocked by

N/A

## 🔍 What does this change?

- Update design of create entity screen to more closely match design
- New `useLoggedInUser` which redirects to login if not logged in
- Updates URLs to `/@shortname/types/new/entity-type` and `/@shortname/types/entity-type/slug` and updates ontology chips
- Makes submitting the create form work, and makes it redirect to the view page
- Make the view page display the entity type title

## 📜 Does this require a change to the docs?

- The docs for x need updating to explain that y

## ⚠️ Known issues

## 🐾 Next steps

Validation

## 🛡 What tests cover this?

N/A

## ❓ How to test this?

1. Create an entity type
2. See that you're redirected to the entity type, and the title displays correctly

2022-10-07 16:03 UTC, nathggns commented on packages/hash/frontend/src/pages/[account-slug]/types/entity-type/[entity-type-id].page.tsx
> +  }
Yeah I completely agree – although I wonder how that works within the idea that this should be a block? Would that mean the entity type would need to be this block's `blockEntity`?

2022-10-07 16:06 UTC, CiaranMn commented on packages/hash/frontend/src/pages/[account-slug]/types/entity-type/[entity-type-id].page.tsx
> +  }
Either the type of the `blockEntity` or of an entity linked to the block (and therefore part of `blockGraph`), e.g. if the `blockEntity` was some wrapping thing that had config about editor state / view preferences, and then the entity to be edited was linked from that.

there's a message called `entityTypes` which is supposed to contain all the types for entities provided as part of `blockEntity` and `blockGraph`, so if the entity being edited is in one of those, its type will be in there

2022-10-10 11:23 UTC, nathggns reviewed
Fix linting

2022-10-10 13:13 UTC, yusufkinatas requested changes
Looks good expect few comments!

2022-10-10 13:13 UTC, yusufkinatas commented on packages/hash/frontend/src/pages/[account-slug]/types/new/entity-type.page.tsx
> +  const [description, setDescription] = useState("");
For the sake of consistency, I think we should use `react-hook-form`'s `useForm` instead of handling user inputs manually with states.

2022-10-10 13:13 UTC, yusufkinatas commented on packages/hash/frontend/src/pages/[account-slug]/types/new/entity-type.page.tsx
> +                },
Do we still need that, since you changed the MUI theme option for this?

2022-10-10 13:13 UTC, yusufkinatas commented on packages/hash/frontend/src/pages/[account-slug]/types/new/entity-type.page.tsx
> +  const [creating, setCreating] = useState(false);
We also don't need this, since `react-hook-form` provides `formState.isSubmitting`

2022-10-10 15:32 UTC, yusufkinatas approved these changes

2022-10-10 15:32 UTC, merged