Add boolean & number type support to entity editor
hashintel/hash pull request #1369
Opened 2022-11-09 11:01 UTC by yusufkinatas

## 🌟 What is the purpose of this PR?

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203150072758509/1203301695650120/f) _(internal)_
- [Design](https://app.asana.com/0/1203150072758509/1203301695650120/f) _(internal)_

## 🔍 What does this change?

- Add `No value` state to value cells
- Move `isValueEmpty` to a separate file
- Add draw & edit support for boolean & number values

## Next Steps

- Match the design of boolean selector 1-1 with design (this PR does not modify the default `Select` style we have in the project)

## ❓ How to test this?

1.  Checkout the branch / view the deployment
1.  Open entity editor with boolean/number types
1.  Confirm that editing/viewing boolean/number types work & look like expected

## 📹 Demo
<img width="848" alt="Screenshot 2022-11-09 at 13 57 28" src="https://user-images.githubusercontent.com/39553853/200812594-c5bebc91-59b0-442f-b6be-ebb82fc540f3.png">
<img width="843" alt="Screenshot 2022-11-09 at 13 57 33" src="https://user-images.githubusercontent.com/39553853/200812600-c1cf020b-8c6f-4142-b1f2-013cc0b1f7ed.png">
<img width="844" alt="Screenshot 2022-11-09 at 13 57 39" src="https://user-images.githubusercontent.com/39553853/200812606-ce3690f3-5836-4448-bc84-60549c645c5b.png">

2022-11-10 09:59 UTC, CiaranMn requested changes
Looking good @yusufkinatas – spotted one thing on the input to fix

We'll also want to think at some point about how we display large numbers when the user isn't editing them - this isn't the most user-friendly (cc @nonparibus)
![Screenshot 2022-11-10 at 09 56 41](https://user-images.githubusercontent.com/37743469/201060541-dd3e80b0-32bd-4b98-9dfc-4890f2065886.png)

2022-11-10 09:59 UTC, CiaranMn commented on packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/cells/value-cell/value-cell-editor/number-or-string-editor.tsx
> +        const newValue = isNumber ? Number(target.value) : target.value;
This makes it impossible to use the keyboard to delete the last number in the cell.

2022-11-10 16:01 UTC, nathggns commented on packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/cells/value-cell.tsx
> +        text: capitalize(String(value)),
This again feels too clever to me – can we just do 

```suggestion
        text: value ? 'True' : 'False',
```

2022-11-14 12:31 UTC, yusufkinatas commented on packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/cells/value-cell/value-cell-editor/boolean-editor.tsx
> +      value={Number(value)}
`MenuItem.value` expects `number | string`, thought 0-1 makes sense for true-false

2022-11-14 13:03 UTC, yusufkinatas commented on packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/cells/value-cell/value-cell-editor/boolean-editor.tsx
> +        const newCell = cloneDeep(cell);
Nope, is it better to use in this case? What's the difference? Afaik `immer` is used to produce a new object from an existing object without modifying the original object. Doesn't `cloneDeep`  does the same thing to cell on this case?

2022-11-14 13:04 UTC, yusufkinatas commented
Thanks for the reviews! Addressed to all the comments.

2022-11-14 13:04 UTC, nathggns commented on packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/cells/value-cell/value-cell-editor/boolean-editor.tsx
> +        const newCell = cloneDeep(cell);
`cloneDeep` clones the entire object – immer just clones the paths that have changed. It'll generally perform better over time. Just not sure why we don't use it.

2022-11-14 13:05 UTC, yusufkinatas commented on packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/cells/value-cell/value-cell-editor/boolean-editor.tsx
> +        const newCell = cloneDeep(cell);
I have no reason for not to use it, just wasn't aware of the difference. Sounds reasonable!

2022-11-14 13:11 UTC, yusufkinatas commented on packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/cells/value-cell/value-cell-editor/boolean-editor.tsx
> +        const newCell = cloneDeep(cell);
Updated here https://github.com/hashintel/hash/pull/1369/commits/54a3337b3c037625c940eadedb27b0ec41554bac

2022-11-14 13:38 UTC, nathggns commented
Reviewing again

2022-11-14 13:40 UTC, nathggns approved these changes

2022-11-14 13:48 UTC, merged