Return incoming links by default
hashintel/hash pull request #1475
Opened 2022-11-23 11:27 UTC by TimDiekmann

## 🌟 What is the purpose of this PR?

We require incoming link edges to be present in the subgraph.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/0/1203426166281269/f) _(internal)_
- [Slack discussion](https://hashintel.slack.com/archives/C03F7V6DU9M/p1669200140528029) _(internal)_

## 🚫 Blocked by

- #1474

## 🔍 What does this change?

- Add a predefined filter to return incoming links by the right entity edition id
- Add edges and linked entities based on that filter

## 🛡 What tests cover this?

None

## ❓ How to test this?

Run the REST endpoint tests and check for the correct edges to be present when querying a person-entity

2022-11-23 11:29 UTC, TimDiekmann commented on packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs
> +                            // outgoing `Link` `Entity`
```suggestion
                            // (HasRightEndpoint, reversed=true) is equivalent to an
                            // incoming link `Entity`
```

2022-11-23 15:34 UTC, Alfred-Mountfield requested changes
One tiny change, otherwise looks good to me (within the context of the current branch, knowing the changes we need to make)

2022-11-23 21:27 UTC, TimDiekmann commented on packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs
> +                            // (HasRightEndpoint, reversed=true) is equivalent to an
Fixed in ab072eb02ed0d460d60d7876b457717559cf68f3

2022-11-24 12:43 UTC, Alfred-Mountfield approved these changes
🚀

2022-11-24 12:43 UTC, merged