Hot-fix: Making state sync sequential with context packages
hashintel/hash pull request #150
Opened 2022-01-11 17:15 UTC by Alfred-Mountfield

## 🌟 What is the purpose of this PR?

When running sims with dynamic initialisations (i.e. using the JS/Py init packages), errors appear with the message batch being unable to acquire write access. 

This happens during the execution of context packages, which happens in parallel to the state-sync. Moving state-sync to happen before context packages seems to fix this. As such this is a hot-fix until we locate the source of the actual problem

## 🔗 Related links

- [Asana task description](https://app.asana.com/0/1199550852792314/1201644875152936/f)
- [Follow up task](https://app.asana.com/0/1199550852792314/1201644875152939/f)

## 🔍 What does this change?

- Awaits state sync before continuing with execution of the context packages

## 🛡 Tests

- ✅ Manual Tests

2022-01-11 17:15 UTC, Alfred-Mountfield commented
Opening as draft until #148 and #149  are enabled to allow proper testing of the PR (although the changes aren't strictly dependent)

2022-01-11 19:06 UTC, litvand requested changes

2022-01-11 19:06 UTC, litvand commented on packages/engine/src/simulation/engine.rs
> +        // TODO: fix issues with getting write access to batch while state sync runs in parallel
```suggestion
        // TODO: fix issues with getting write access to the context batch while state sync runs in parallel
```

2022-01-11 19:06 UTC, litvand commented on packages/engine/src/simulation/engine.rs
> +        //   with the context batch
```suggestion
        //   with context packages
```

2022-01-12 10:38 UTC, litvand approved these changes

2022-01-12 10:43 UTC, merged