Support editing property types with property objects or arrays
hashintel/hash pull request #1769
Opened 2023-01-05 15:21 UTC by nathggns

## 🌟 What is the purpose of this PR?

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203363157432084/1203554268413277/f) _(internal)_

## 🚫 Blocked by

- [ ] ...

## 🔍 What does this change?

- ...

## 📜 Does this require a change to the docs?

- The docs for x need updating to explain that y

## ⚠️ Known issues

## 🐾 Next steps

## 🛡 What tests cover this?

-

## ❓ How to test this?

1.  Checkout the branch / view the deployment
1.  Try X
1.  Confirm that Y

## 📹 Demo

2023-01-05 16:29 UTC, nathggns commented on packages/hash/frontend/src/pages/[shortname]/types/entity-type/[entity-type-id].page/definition-tab/property-list-card/shared/get-expected-value-descriptor.ts
> +import { dataTypeOptions } from "./data-type-options";
This code is all abstracted from `custom-expected-value-builder`

2023-01-05 16:36 UTC, nathggns commented on packages/hash/frontend/src/pages/[shortname]/types/entity-type/[entity-type-id].page/definition-tab/property-list-card/get-property-type-schema.ts
> +import {
Most of this comes from the `property-type-schema` file which has been deleted.

2023-01-09 10:19 UTC, nathggns commented on packages/hash/frontend/src/pages/[shortname]/types/entity-type/[entity-type-id].page/definition-tab/property-list-card/property-type-to-form-data-expected-values.ts
> +import {
I think I do disagree. The variables it mutates are redefined on each call to `propertyTypeToFormDataExpectedValues`, and `processProperties` is only available within the scope of `propertyTypeToFormDataExpectedValues`. Cloning and merging arrays at every depth levels seems a) more complex and b) slower and c) harder to read. Going to leave as it is for now. 

I'm also wary of mutation generally, but mutation of locally owned variables when building new values is performant and sensible.

2023-01-09 19:50 UTC, luisbettencourt requested changes
Thank you for fixing the issue @nathggns, and nice thinking splitting up the context in two!
Should be good to go after fixing the linting issue

2023-01-09 20:23 UTC, luisbettencourt approved these changes

2023-01-09 20:23 UTC, merged