Add all fields for `Tool` struct
hashintel/hash pull request #2245
Opened 2023-03-21 00:54 UTC by TimDiekmann

## 🌟 What is the purpose of this PR?

This exhaustively adds all fields to the `Tool` struct and the API around it

## 🚫 Blocked by

- #2243 

## 🔍 What does this change?

- Add `PropertyBag`
- Add fields to `Tools`
- Greatly extend documentation and tests

2023-03-21 10:02 UTC, indietyp requested changes
looks good overall

2023-03-21 10:02 UTC, indietyp commented on libs/sarif/src/schema/run.rs
> +    ///
Run as a missing property bag. (see note about `3.8`)

2023-03-21 10:02 UTC, indietyp commented on libs/sarif/src/schema/tool.rs
> +    ///
Run as a missing property bag. (see note about `3.8`)

2023-03-21 14:46 UTC, TimDiekmann commented on libs/sarif/src/schema/properties.rs
> +impl PropertyBag {
I marked all types, which are not fully implemented yet, as non-exhaustive, so I'll add `PropertyBag` to them later.

2023-03-22 09:32 UTC, indietyp approved these changes

2023-03-22 09:32 UTC, indietyp commented on libs/sarif/src/schema/tool.rs
> +    pub fn with_extensions(mut self, extension: impl IntoIterator<Item = ToolComponent>) -> Self {
consistent w/ #2243, therefore fine keeping it

2023-03-22 10:15 UTC, indietyp approved these changes

2023-03-22 10:42 UTC, merged