Support `version` and `semantic_version` in `ToolComponent`
hashintel/hash pull request #2246
Opened 2023-03-21 01:31 UTC by TimDiekmann

## 🌟 What is the purpose of this PR?

This further extends the `ToolComponent` struct

## 🚫 Blocked by

- #2243
- #2244

## 🔍 What does this change?

- Add `ToolComponent::version`
- Add `ToolComponent::semantic_version`
- Add builder methods and documentation
- Add to the `full` test

## 🛡 What tests cover this?

- This branch has 💯% test coverage

2023-03-21 10:05 UTC, indietyp requested changes

2023-03-21 10:05 UTC, indietyp commented on libs/sarif/src/schema/log.rs
I like how you're using a realist example for full! :D

2023-03-21 10:05 UTC, indietyp commented on libs/sarif/src/schema/tool.rs
>  pub struct ToolComponent {
`3.19.2`: "At least one of version (§3.19.13) and semanticVersion (§3.19.12) SHOULD be present" this invariant is not upheld in the constructor (or by having publicly accessible fields)

2023-03-21 10:13 UTC, indietyp commented on libs/sarif/src/schema/tool.rs
>  pub struct ToolComponent {
This is wrong, I (once again), have mistaken `SHOULD` for `SHALL` (which while being very similar have a totally different meaning). So we do not need to ensure that at least one of them exists. My bad! I am fine with the current version!

2023-03-21 10:14 UTC, indietyp approved these changes

2023-03-21 14:48 UTC, TimDiekmann commented on libs/sarif/src/schema/log.rs
Actually, I haven't found any examples, but would `prettier-plugin-sql` be an extension?

2023-03-21 14:59 UTC, indietyp commented on libs/sarif/src/schema/log.rs
I think so, yes.

2023-03-22 14:06 UTC, indietyp approved these changes

2023-03-22 14:19 UTC, merged