Move GitHub files out of root
hashintel/hash pull request #2347
Opened 2023-04-02 13:58 UTC by nonparibus

## 🌟 What is the purpose of this PR?

Mirrors https://github.com/blockprotocol/blockprotocol/pull/1240 in the HASH repo.

2023-04-02 14:53 UTC, TimDiekmann requested changes

2023-04-02 14:53 UTC, TimDiekmann commented on README.md
> +Please see [SECURITY](.github/.github/SECURITY.md) for instructions around reporting issues, and details of which package versions we actively support.
```suggestion
Please see [SECURITY](.github/SECURITY.md) for instructions around reporting issues, and details of which package versions we actively support.
```

2023-04-02 14:53 UTC, TimDiekmann approved these changes

2023-04-02 14:57 UTC, nonparibus commented on README.md
> +Please see [SECURITY](.github/.github/SECURITY.md) for instructions around reporting issues, and details of which package versions we actively support.
Good spot, ty!

2023-04-06 20:35 UTC, hashdotai approved these changes

2023-04-06 21:02 UTC, merged