parse query macro attributes
hashintel/hash pull request #2394
Opened 2023-04-11 12:57 UTC by indietyp

## 🌟 What is the purpose of this PR?

This parses the enum definition (and attributes) into a couple of types, which are then used to create the generated types.

## 🚀 Has this modified a publishable library?

This PR:

- [ ] modifies an **npm**-publishable library and **I have added a changeset file(s)**
- [ ] modifies a **Cargo**-publishable library and **I have amended the version**
- [ ] modifies a **Cargo**-publishable library, but **it is not yet ready to publish**
- [ ] modifies a **block** that will need publishing via GitHub action once merged
- [x] does not modify any publishable blocks or libraries
- [ ] I am unsure / need advice

2023-04-11 22:02 UTC, TimDiekmann requested changes
Generally, the PR looks good but currently has merge conflicts and lints failing. 
Are you planning on do more testing and check if the output is the expected output? I'm fine with doing this in a follow-up.

2023-04-12 06:39 UTC, indietyp commented
Yes, the plan is to also test the expanded output, though I haven't been able to find a good similar library to expect-test that does that.

Will fix the lints and merge conflicts!

2023-04-12 07:33 UTC, indietyp commented
The plan in general is to 

(A) have pass UI tests (can I access the built type?, did everything compile?)
(B) observe behaviour (when using the derive macro, is the builder working, etc.)

2023-05-09 16:22 UTC, TimDiekmann approved these changes

2023-05-09 17:18 UTC, merged