Syncing between `Cargo.toml` and `package.json` files.
hashintel/hash pull request #4338
Opened 2024-04-21 16:16 UTC by indietyp

## 🌟 What is the purpose of this PR?

While creating the `harpc` wire protocol #4283 I was a bit annoyed about the error-prone nature of defining a `package.json` file and keeping that file up to date with all the dependencies.

So I thought: hey isn't this something one can automate. Introducing: this very PR.

It adds a new script (`sync-turborepo.rs`), which takes the settings from the Rust `Cargo.toml` and writes them to the `package.json`. This is as close as I could get to native Rust support.

To determine package names easier and consistent across `package.json` and `Cargo.toml` boundaries, I introduced the `@rust` namespace in `package.json`. This might be a bit contentious, but it can be changed.

## 🔍 What does this change?

* `package.json` files are being derived from `Cargo.toml`

## Pre-Merge Checklist 🚀

### 🚢 Has this modified a publishable library?

This PR:

- [x] does not modify any publishable blocks or libraries, or modifications do not need publishing

### 📜 Does this require a change to the docs?

The changes in this PR:

- [x] are internal and do not require a docs change

### 🕸️ Does this require a change to the Turbo Graph?

The changes in this PR:

- [x] affected the execution graph, and the `turbo.json`'s have been updated to reflect this

## ⚠️ Known issues

* To keep the name of crates in line with packages, `@rust` has been introduced as a namespace

## 🐾 Next steps

* Integration into CI
* prettier on changed files

## ❓ How to test this?

See 5eeec0a879d4852aade937cb2333693c615a42f3 for the output.

2024-04-21 16:49 UTC, TimDiekmann reviewed
It's pretty nice to have the dependencies being automated. I, however, am not sure if we should rename the dependencies from `@local/...` to `@rust/...`, but I don't dislike it. I defer to @CiaranMn for this. Also, I'm unsure about adding new `package.json` for projects which meant to be part of `apps/hash-graph`. The plan is to move out these crates anyway so I don't feel strongly about this and is probably easier to just keep them.

2024-04-21 16:52 UTC, indietyp commented
I've mainly added them because it makes it easier to define the dependencies that way. You still need to manually add them to the `package.json`, but dependencies between the packages will be tracked correctly. So it's a trade-off I guess.

2024-04-22 09:12 UTC, CiaranMn approved these changes
> I, however, am not sure if we should rename the dependencies from @local/... to @rust/..., but I don't dislike it. I defer to @CiaranMn for this

I don't think we should rename these packages in isolation. The package names currently follow the folder structure, and this would break it, as well as introducing other inconsistencies between these and other packages (some packages named after their language, some not).

I think we should only change them as part of some wider restructuring of how we rename packages, but I'm not sure there's a particular need to take that on at the moment, unless the current format is causing problems that some better structure will solve

2024-04-22 09:13 UTC, CiaranMn requested changes
Meant https://github.com/hashintel/hash/pull/4338#pullrequestreview-2014218372 to just be a comment, sorry 😓

2024-04-22 10:08 UTC, indietyp commented
> > I, however, am not sure if we should rename the dependencies from @local/... to @rust/..., but I don't dislike it. I defer to @CiaranMn for this
> 
> I don't think we should rename these packages in isolation. The package names currently follow the folder structure, and this would break it, as well as introducing other inconsistencies between these and other packages (some packages named after their language, some not).
> 
> I think we should only change them as part of some wider restructuring of how we rename packages, but I'm not sure there's a particular need to take that on at the moment, unless the current format is causing problems that some better structure will solve

But these packages/crates are already not wholly consistent. We have some packages that do not follow the naming scheme of `-rs` (see `hash-graph`), some have `-rust` as suffix and some have `-rs` as suffix. This introduces greater consistency by saying: the name in a cargo workspace must be unique (this is something we can guarantee), but we cannot guarantee that any name in `@local`, `@libs` or `@apps` is unique (if derived from the rust package name). Therefore, adding the namespace `@rust` introduces an easy way to ensure that the name is unique (it also makes the naming logic quite a bit easier).

We also never actually want to reference Rust packages in, for example, the JS namespace, so you introduce a separation layer. The `package.json` is not there to interact with the yarn workspace, really, but to register them to turborepo.

Those were at least my thoughts. Of course, I can also change the logic to use a uniform `-rs` suffix and `@local`, `@libs`, and `@apps`, although the logic will be more brittle.

2024-04-22 14:59 UTC, CiaranMn reviewed
> Of course, I can also change the logic to use a uniform -rs suffix and @local, @libs, and @apps, although the logic will be more brittle.

What is it about the logic that would be more brittle?

The current convention (which I appreciate is not written down) is as follows:
- `@apps/` are executable things
- `@local/` are dependencies in this repo of other things in the repo
- `@anything-else/` is a published dependency of other things

`@local/` just makes it easier to see which dependencies in a JS/TS package are internal, and which are coming from npm. I appreciate this it not a consideration for Rust since Cargo doesn't have namespacing like that.

If we change Rust packages to `@rust/`, we lose the 'app' vs 'lib' distinction. I am not totally opposed to this, but I'd like to understand more what it is about a `-rs` or `-rust` suffix that would be worse, and which makes changing the existing pattern worth it. We would also need to decide what to do about `apps/hash-graph/package.json`, which currently is still named `@apps/hash-graph`.

2024-04-22 14:59 UTC, CiaranMn commented on .github/scripts/rust/sync-turborepo.rs
> +            || dependencies.starts_with("@libs/")
```suggestion
        // @blockprotocol, @rust, @local, @apps, @repo
        dependencies.starts_with("@blockprotocol/")
            || dependencies.starts_with("@rust/")
            || dependencies.starts_with("@local/")
```

2024-04-22 15:17 UTC, indietyp commented
instead of simply relying on the crate and `Cargo.toml` itself, we would need to look at the back and then decide if it is in the path `apps/` or `libs/@local`, which makes it a bit more complicated (which is already done). Any change in directory structure or moving of packages then potentially involves the renaming of crates. While not a problem for the script, other dependents (which shouldn't exist) won't get those.

Current `hash-graph` still remains, but this is also where the `apps` vs. `libs` distinction breaks down, we wanted to move this stuff anyway, but `hash-graph/libs/graph` would in theory be a `@local/hash-graph-rs`, which means it would need special casing. Then the question remains, is `@apps/hash-graph`, while `hash-graph/bins/cli` would need to be named `@apps/hash-graph-rs`, because `@apps/hash-graph` is already taken. Putting all crates under `@rust` in the package name would solve this issue. Another thing to consider here is that while the distinction exists in the fs structure, it doesn't necessarily exist in a cargo workspace, and as rust crates don't interact with any other languages (exception here is the WASM type-system) I don't really see how there's a benefit in the naming using `@local` or `@apps`, if that name won't ever be used anyway (although I appreciate that it creates a more cohesive system of separation nevertheless, even if not used.)

I won't ever address a cargo crate by `@apps/hash-graph`, I will via `hash-graph`, as namespaces like that simply don't exist in Rust. So a distinction on `package.json` level doesn't really help here in any scenario I can think of.

I hope this makes sense.

2024-04-24 12:03 UTC, CiaranMn approved these changes
> I hope this makes sense.

Thanks @indietyp, yes it does make sense. Happy to go with the `@rust/` prefix then. Apologies in the delay in responding, I didn't get a notification which I normally rely on

2024-04-24 16:01 UTC, CiaranMn approved these changes

2024-04-24 16:30 UTC, merged