HASH.dev Homepage
hashintel/hash pull request #464
Opened 2022-04-05 01:36 UTC by nathggns

## 🌟 What is the purpose of this PR?

Introduces a new HASH.dev NextJS site consisting of a landing page, with the ability to subscribe to our newsletter and be tagged as a HASH.dev user. Also includes a Storybook instance. 

## ⚠️ Known issues

Having to use a alpha version of Storybook, and also pinning to an out of scope version of Prettier to fix an issue. 

## 🚫 Blocked by

N/A

## 🐾 Next steps

Introduction of a blog

## 🔍 What does this change?

Nothing – all new. 

### 📜 Does this require a change to the docs?

No

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1201927504137297/1201694916711102/f) _(internal)_

## 🛡 What tests cover this?

- None

## ❓ How to test this?

Check it matches figma design. 

## 📹 Demo

![localhost_3000_ (8)](https://user-images.githubusercontent.com/719814/161662134-4853a487-10c8-4c51-827f-8ce0f083ddff.png)

2022-04-05 07:08 UTC, nonparibus commented
@nathggns Any idea why deployment has failed? @MaggieAppleton and I will wait on review until then.

2022-04-05 09:21 UTC, nonparibus commented
@nathggns When there's a deploy link can you stick it here? I can't see one at https://vercel.com/hashintel/hashdev

2022-04-05 09:25 UTC, nathggns commented
@nonparibus @MaggieAppleton Deployment is at https://dev-taupe.vercel.app/ – The URL is linked to this branch, and the fontawesome kit is set up to work on that URL. I haven't yet figured out how to make the fontawesome kit work with commit deployments.

2022-04-05 09:35 UTC, nonparibus commented on sites/dev/src/components/Footer.tsx
> +              Terms of Service
```suggestion
              Terms
```

Can we shorten this to 'Terms' and also add a 'Privacy' link beneath pointing to https://hash.ai/legal/privacy

2022-04-05 09:37 UTC, nonparibus commented
Can we change the linked word 'HASH' in the sentence "HASH is an organization building" to point to https://hash.ai/about? Given the paragraph provides context to the org itself, I feel this is the appropriate page to link out to.

2022-04-05 09:39 UTC, nonparibus requested changes
At some screen sizes the whitespacing beneath the HASH project GitHub button seems to screw up. Generally this is good-to-go, though. Left a couple of other comments separately re: new/changing links.
 
<img width="1127" alt="Screenshot 2022-04-05 at 10 38 32" src="https://user-images.githubusercontent.com/6226576/161725767-191379ba-a51b-45d8-9b07-fc37385d0c34.png">

2022-04-05 12:52 UTC, nathggns commented
> At some screen sizes the whitespacing beneath the HASH project GitHub button seems to screw up. Generally this is good-to-go, though. Left a couple of other comments separately re: new/changing links.

Thanks for this. It's one of the known issues I mentioned which I thought you didn't want me to spend time fixing, but I'll take a look. 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/719814/161757751-5d82e503-7e61-405e-b627-1b5b0fedca51.png">

2022-04-05 16:29 UTC, nonparibus commented on sites/dev/src/pages/index.page.tsx
> +                Download on Github
```suggestion
                Download on GitHub
```

2022-04-05 16:29 UTC, nonparibus commented on sites/dev/src/pages/index.page.tsx
> +                Download on Github
```suggestion
                Download on GitHub
```

2022-04-06 14:20 UTC, nonparibus approved these changes

2022-04-07 13:14 UTC, nonparibus submitted a review, later dismissed

2022-04-07 13:14 UTC, nonparibus commented
@CiaranMn When this has merged let's change the Vercel deployment to point back to the `main` branch, and ice the temporary deploy branch. Thanks again for your help in getting this up on Tue night.

2022-04-07 15:16 UTC, MaggieAppleton commented
This all looks great to me. Nice job @nathggns ! 🎉

2022-04-07 15:17 UTC, MaggieAppleton approved these changes

2022-04-07 15:36 UTC, merged