Add LICENSE.md for error-stack
hashintel/hash pull request #618
Opened 2022-06-07 15:27 UTC by TimDiekmann

## 🌟 What is the purpose of this PR?

Releases `error-stack` under an MIT license.

## 🔍 What does this change?

- Add *LICENSE.md*
- Mention the license on *Cargo.toml* (required for releasing)

2022-06-07 16:20 UTC, Alfred-Mountfield requested changes

2022-06-07 16:26 UTC, Alfred-Mountfield requested changes
As expressed off Slack I think we should re-work the layout of this README heavily to guide people more towards quick-start usage, and moving specifics into supplementary files. 

I also think we should spend less time comparing with other libraries and justifying design decisions in the README, making sure that we make that capture that information elsewhere (docs, supplementary files and/or by pointing people to the announcement)

2022-06-07 17:34 UTC, nonparibus commented on packages/libs/error-stack/README.md
> +Having the concept of `error-stack` explain, these are the functionalities we also provide. Don't forget to checkout the [documentation] as well!
The first sentence here reads incorrectly; unsure of best/exact intended phrasing.

2022-06-07 17:39 UTC, nonparibus commented on packages/libs/error-stack/README.md
> +## What’s the catch?
I don't object to keeping some sort of 'Considerations' section in the main README, which I think done a bit more broadly -- as opposed to focused solely on performance -- would be helpful reading to anyone considering adopting the library.

2022-06-07 17:42 UTC, nonparibus commented
I agree with the part of Alfie's top-level review comment which states we should link to the announcement post for discussion of alternative solutions/additional contextual information.

However I would not split 'Performance' out into another file -- instead making it more concise and folding it into a 'Considerations' section containing things potential adopters should consider.

2022-06-09 16:22 UTC, TimDiekmann commented
Removed README.md in favor of #587

2022-06-09 16:28 UTC, Alfred-Mountfield approved these changes

2022-06-09 16:28 UTC, nonparibus approved these changes

2022-06-09 16:54 UTC, merged