Fix the `multiple_runners` test.
hashintel/hash pull request #948
Opened 2022-08-17 15:27 UTC by teymour-aldridge

## 🌟 What is the purpose of this PR?

Fixes the `multiple_runners` test.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1199548034582004/1202815168504002) _(internal)_

## 🔍 What does this change?

- Fixes a bug which would happen when trying to use Python and JavaScript runners together.

## 🛡 What tests cover this?

- The test suite (and specifically the `multiple_runners` test)

2022-08-18 10:17 UTC, Alfred-Mountfield reviewed
Generally looks good to me :) I think @TimDiekmann should have a look at this one too though

2022-08-18 10:17 UTC, Alfred-Mountfield commented on packages/engine/lib/execution/src/package/simulation/state/behavior_execution/reset_index_col.rs
> +/// the behaviour list).
Can you clarify this a little more? I don't quite understand it

2022-08-18 10:17 UTC, Alfred-Mountfield commented on packages/engine/lib/execution/src/runner/javascript/mod.rs
> +    /// See also the [`memory::arrow::flush`] module for more information.
Appreciate the drive-by doc improvements, thank you!

2022-08-18 10:25 UTC, TimDiekmann requested changes
LGTM, thank you!

Only have two minor things on creating the error.

2022-08-18 10:25 UTC, TimDiekmann commented on packages/engine/lib/execution/src/runner/javascript/mod.rs
> +            JavaScriptError::Unique("could not reload batches (this is a bug)".to_string())
```suggestion
            JavaScriptError::from("could not reload batches (this is a bug)")
```

2022-08-18 10:25 UTC, TimDiekmann commented on packages/engine/lib/execution/src/task/shared_store.rs
> +        crate::runner::JavaScriptError::Unique("cannot obtain the state as writable".to_owned())
```suggestion
        crate::runner::JavaScriptError::from("cannot obtain the state as writable")
```

2022-08-19 09:30 UTC, TimDiekmann approved these changes
🎉

2022-08-19 10:05 UTC, merged